/**
 * 
 */
package com.anil.jmx;

import javax.management.AttributeChangeNotification;
import javax.management.MBeanNotificationInfo;
import javax.management.Notification;
import javax.management.NotificationBroadcasterSupport;

/**
 * The implementing class for the MBean interface that we defined. This would be
 * registered with the platform Mbean server so that it can be managed by the
 * JMX agent that we use.<br>
 * <br>
 * 
 * For standard Java applications we will use the JConsole executable that comes
 * bundled with JDK<br>
 * <br>
 * 
 * The attibutes provided with getter/setter are available as attributes that
 * can be changed if you have provided the setter methods for those.
 * 
 * The other method are available as operations that can be invoked e.g.
 * sayHello()
 * 
 * @author anila
 */
public class JMXHello extends NotificationBroadcasterSupport implements
		JMXHelloMBean {

	private static final int DEFAULT_CACHE_SIZE = 200;
	private int cacheSize = DEFAULT_CACHE_SIZE;
	private String name;
	private int sequenceNumber;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.anil.jmx.JMXHelloMBean#getCache()
	 */
	public int getCache() {
		return this.cacheSize;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.anil.jmx.JMXHelloMBean#getName()
	 */
	public String getName() {
		return this.name;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.anil.jmx.JMXHelloMBean#sayHello()
	 */
	public void sayHello() {
		System.out.println("The sayHello() method was called.");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.anil.jmx.JMXHelloMBean#add()
	 */
	public int add(int x, int y) {
		return x + y;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.anil.jmx.JMXHelloMBean#setCache(int)
	 */
	public void setCache(int cacheSize) {
		int oldCacheSize = this.cacheSize;
		this.cacheSize = cacheSize;
		System.out.println("setCache() called with value: " + cacheSize);

		// Send out a notification
		Notification n = new AttributeChangeNotification(this,
				this.sequenceNumber++, System.currentTimeMillis(),
				"Cache Size changed", "Cache Size", "int", oldCacheSize,
				this.cacheSize);

		sendNotification(n);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.anil.jmx.JMXHelloMBean#setName(java.lang.String)
	 */
	public void setName(String name) {
		this.name = name;
		System.out.println("setName() called with value: " + name);
	}

	@Override
	public MBeanNotificationInfo[] getNotificationInfo() {
		String[] types = new String[] { AttributeChangeNotification.ATTRIBUTE_CHANGE };

		String name = AttributeChangeNotification.class.getName();
		String description = "An attribute of this MBean has changed";
		/*
		 * MBeanNotificationInfo instance is defined to describe the
		 * characteristics of the different notification instances generated by
		 * the MBean for a given type of notification. In this case the type of
		 * notifications sent is AttributeChangeNotification notifications.
		 */
		MBeanNotificationInfo info = new MBeanNotificationInfo(types, name,
				description);
		return new MBeanNotificationInfo[] { info };
	}
}
